# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.WASMVM_VERSION }}/libwasmvm_muslc.x86_64.a -O /lib/libwasmvm_muslc.a
    - apk add gcc
env:
  - CGO_ENABLED=1

git:
  # What should be used to sort tags when gathering the current and previous
  # tags if there are more than one tag in the same commit.
  #
  # Default: '-version:refname'
  # Source: https://goreleaser.com/customization/git/
  tag_sort: -version:creatordate

builds:
  - main: ./cmd/palomad
    binary: palomad
    tags:
      - netgo
      - gcc
      - ledger
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=paloma
      - -X github.com/cosmos/cosmos-sdk/version.AppName=palomad
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Tag }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .FullCommit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer={{ .Env.COMETBFT_VERSION }}
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs --static'
    goos:
      - linux
    goarch:
      - amd64


archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^third_party_proto:'
      - '^testutil:'
      - '^scripts:'
      - '^docs:'
