# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - sudo wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.WASMVM_VERSION }}/libwasmvm_muslc.{{ .Env.KERNEL_MACHINE }}.a -O /lib/libwasmvm.{{ .Env.KERNEL_MACHINE }}.a
    - sudo apt-get update && sudo apt-get install -y gcc musl musl-tools
env:
  - CGO_ENABLED=1
  - CC=musl-gcc

builds:
  - main: ./cmd/palomad
    binary: palomad
    tags:
      - netgo
      - gcc
      - ledger
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=paloma
      - -X github.com/cosmos/cosmos-sdk/version.AppName=palomad
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Tag }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .FullCommit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer={{ .Env.COMETBFT_VERSION }}
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs --static -lm'
    goos:
      - linux
    goarch:
      - amd64
    # buildmode: c-archive


archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^third_party_proto:'
      - '^testutil:'
      - '^scripts:'
      - '^docs:'
