# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.WASMVM_VERSION }}/libwasmvm_muslc.x86_64.a -O /tmp/libwasmvm_muslc.a
    - mkdir -p /tmp/lib/
    - mv /tmp/libwasmvm_muslc.a /tmp/lib/libwasmvm_muslc.a
    - apk add gcc
    - export LIBRARY_PATH=/tmp/lib:$LIBRARY_PATH
    - export LD_LIBRARY_PATH=/tmp/lib:$LD_LIBRARY_PATH
env:
  - CGO_ENABLED=1

builds:
  - main: ./cmd/palomad
    binary: palomad
    tags:
      - netgo
      - gcc
      - ledger
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=paloma
      - -X github.com/cosmos/cosmos-sdk/version.AppName=palomad
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Tag }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .FullCommit }}
      - -X github.com/cosmos/cosmos-sdk/version.BuildTags=netgo
      - -X github.com/cometbft/cometbft/version.TMCoreSemVer={{ .Env.COMETBFT_VERSION }}
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs --static'
    goos:
      - linux
    goarch:
      - amd64


archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^third_party_proto:'
      - '^testutil:'
      - '^scripts:'
      - '^docs:'
